# Generated by Django 5.2 on 2025-09-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
