# Generated by Django 5.2 on 2025-09-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='tags',
        ),
    ]
