# Generated by Django 5.2 on 2025-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
