# Generated by Django 5.2 on 2025-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_audio_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
