# Generated by Django 5.2 on 2025-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_extract_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_format_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_transcribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('download', 'Download'), ('upload', 'Upload to Ceph'), ('inactive', 'Inactive'), ('transcribe', 'Transcribe'), ('format_text', 'Format text'), ('is_extract_note', 'Extract note'), ('finish', 'Finish')], default='active', max_length=20),
        ),
    ]
