# Generated by Django 5.2 on 2025-09-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_is_extract_note_lesson_is_format_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='raw_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
