# Generated by Django 5.2 on 2025-09-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_raw_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('download', 'Download'), ('upload', 'Upload to Ceph'), ('transcribe', 'Transcribe'), ('format_text', 'Format text'), ('is_extract_note', 'Extract note'), ('enbale', 'Enable'), ('disable', 'Disable')], default='init', max_length=20),
        ),
    ]
