# Generated by Django 5.2 on 2025-09-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_extract_note',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_format_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_transcribe',
        ),
    ]
