# Generated by Django 5.2 on 2025-09-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_remove_lesson_is_extract_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='vocabulary',
        ),
        migrations.AddField(
            model_name='lesson',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vocabulary_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='VocabularyItem',
        ),
    ]
