# Generated by Django 5.2 on 2025-09-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_lesson_vocabulary_lesson_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='note',
            new_name='notes',
        ),
    ]
