# Generated by Django 5.2 on 2025-09-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_rename_note_lesson_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Audio',
        ),
    ]
