# Generated by Django 5.2 on 2025-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_rename_lesson_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='uploaded_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
