# Generated by Django 5.2 on 2025-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_audio_uploaded_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='local_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
