# Generated by Django 5.2 on 2025-10-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_category_remove_audio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.category'),
        ),
    ]
