# Generated by Django 5.2 on 2025-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_audio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'english'), ('GERMAN', 'german')], default='ENGLISH', max_length=30),
        ),
    ]
