# Generated by Django 5.2 on 2025-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_tag_speaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaking',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
