# Generated by Django 5.2 on 2025-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_speaking_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaking',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
