# Generated by Django 5.2 on 2025-10-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_alter_speaking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaking',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('GENERATE_TEXT', 'GENERATE TEXT'), ('enbale', 'Enable'), ('disable', 'Disable')], default='init', max_length=20),
        ),
    ]
