# Generated by Django 5.2 on 2025-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_speaking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lessons.tag'),
        ),
        migrations.AddField(
            model_name='speaking',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
