# Generated by Django 5.2 on 2025-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_audio_tags_speaking_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcript_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('download', 'Download'), ('upload', 'Upload to Ceph'), ('transcribe', 'Transcribe'), ('format_text', 'Format text'), ('is_extract_note', 'Extract note'), ('translate_text', 'Translate text'), ('enbale', 'Enable'), ('disable', 'Disable')], default='init', max_length=20),
        ),
    ]
