# Generated by Django 5.2 on 2025-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_remove_speaking_prompt_instructions_speakinganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaking',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
