# Generated by Django 5.2 on 2025-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_speaking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinganswer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lessons.tag'),
        ),
    ]
