services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ASSEMBLYAI_TOKEN=955dcef15e0a47459ab11470d2c5eadb 
      - GAPGPT_TOKEN=sk-hux5OfXRoikXZFIsRTOfCslLvyayOTp2tYWsuBx5HCX0Zne1
      - BOTO3_ARVAN_ACCESS_KEY=c13e1dd1-65f7-4a75-8e8d-41838b2f9150
      - BOTO3_ARVAN_SECRET_KEY=798bb8ad2e09b10b4881332f1db9dff7fcef2499e93ecc5025b8508bfb67f1a4
      - ARVAN_S3_DOMAIN=https://enhubs23.s3.ir-thr-at1.arvanstorage.ir
      - ARVAN_S3_BUCKET=enhubs23
    depends_on:
      - db
      - redis
    networks:
      - app_network

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BOTO3_ARVAN_ACCESS_KEY=c13e1dd1-65f7-4a75-8e8d-41838b2f9150
      - BOTO3_ARVAN_SECRET_KEY=798bb8ad2e09b10b4881332f1db9dff7fcef2499e93ecc5025b8508bfb67f1a4
      - ARVAN_S3_DOMAIN=https://enhubs23.s3.ir-thr-at1.arvanstorage.ir
      - ARVAN_S3_BUCKET=enhubs23
    networks:
      - app_network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    external: true
