# Generated by Django 5.2 on 2025-10-20 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitnerbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
