# Generated by Django 5.2 on 2025-11-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitnerbox', '0002_card_next_review_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='llm_extractions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
