# Generated by Django 5.2 on 2025-11-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitnerbox', '0003_card_llm_extractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='lessonId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
